// Mirrors modules/services/invoicing/paystack_subaccount_service.py
// PaystackSubaccountService.BANK_NAME_MAP exactly — there's no banks-list
// endpoint on the backend, so this is the same fixed map the backend itself
// resolves bank_name from. Keep in sync if that map changes.

// Auto-generated from Paystack GET /bank (NGN) — last synced 2026-07-05
// Source: Paystack Bank List API (https://api.paystack.co/bank?currency=NGN)
export const NIGERIAN_BANKS: { code: string; name: string }[] = [
  { code: "40195", name: "78 Finance Company Ltd" },
  { code: "090629", name: "9jaPay Microfinance Bank" },
  { code: "120001", name: "9mobile 9Payment Service Bank" },
  { code: "404", name: "Abbey Mortgage Bank" },
  { code: "51204", name: "Above Only MFB" },
  { code: "51312", name: "Abulesoro MFB" },
  { code: "044", name: "Access Bank" },
  { code: "063", name: "Access Bank (Diamond)" },
  { code: "602", name: "Accion Microfinance Bank" },
  { code: "90102", name: "Adamawa Mortgage Bank Limited" },
  { code: "50315", name: "Aella MFB" },
  { code: "90077", name: "AG Mortgage Bank" },
  { code: "50036", name: "Ahmadu Bello University Microfinance Bank" },
  { code: "120004", name: "Airtel Smartcash PSB" },
  { code: "51336", name: "AKU Microfinance Bank" },
  { code: "090561", name: "Akuchukwu Microfinance Bank Limited" },
  { code: "50055", name: "Al-Barakah Microfinance Bank" },
  { code: "035A", name: "ALAT by WEMA" },
  { code: "51074", name: "Alert MFB" },
  { code: "108", name: "Alpha Morgan Bank" },
  { code: "000304", name: "Alternative bank" },
  { code: "50926", name: "Amju Unique MFB" },
  { code: "50083", name: "Aramoko MFB" },
  { code: "401", name: "ASO Savings and Loans" },
  { code: "50092", name: "Assets Microfinance Bank" },
  { code: "MFB50094", name: "Astrapolaris MFB LTD" },
  { code: "090478", name: "AVUENEGBE MICROFINANCE BANK" },
  { code: "51351", name: "AWACASH MICROFINANCE BANK" },
  { code: "51337", name: "AZTEC MICROFINANCE BANK LIMITED" },
  { code: "51229", name: "Bainescredit MFB" },
  { code: "50117", name: "Banc Corp Microfinance Bank" },
  { code: "11072", name: "Bank78 Microfinance Bank" },
  { code: "50572", name: "BANKIT MFB" },
  { code: "50572", name: "BANKIT MICROFINANCE BANK LTD" },
  { code: "51341", name: "BANKLY MFB" },
  { code: "MFB50992", name: "Baobab Microfinance Bank" },
  { code: "51100", name: "BellBank Microfinance Bank" },
  { code: "51267", name: "Benysta Microfinance Bank Limited" },
  { code: "50122", name: "Berachah Microfinance Bank Ltd." },
  { code: "50123", name: "Beststar Microfinance Bank" },
  { code: "50725", name: "BOLD MFB" },
  { code: "51449", name: "Boost Microfinance Bank" },
  { code: "650", name: "Bosak Microfinance Bank" },
  { code: "50931", name: "Bowen Microfinance Bank" },
  { code: "FC40163", name: "Branch International Finance Company Limited" },
  { code: "90070", name: "Brent Mortgage bank" },
  { code: "50645", name: "BuyPower MFB" },
  { code: "565", name: "Carbon" },
  { code: "51353", name: "Cashbridge Microfinance Bank Limited" },
  { code: "865", name: "CASHCONNECT MFB" },
  { code: "51437", name: "Cedrus MFB" },
  { code: "50823", name: "CEMCS Microfinance Bank" },
  { code: "050032", name: "Centrum Finance" },
  { code: "50171", name: "Chanelle Microfinance Bank Limited" },
  { code: "312", name: "Chikum Microfinance bank" },
  { code: "023", name: "Citibank Nigeria" },
  { code: "070027", name: "CITYCODE MORTAGE BANK" },
  { code: "50910", name: "Consumer Microfinance Bank" },
  { code: "51458", name: "Cool Microfinance Bank Limited" },
  { code: "90089", name: "Cooperative Mortgage Bank" },
  { code: "50204", name: "Corestep MFB" },
  { code: "559", name: "Coronation Merchant Bank" },
  { code: "FC40128", name: "County Finance Limited" },
  { code: "40119", name: "Credit Direct Limited" },
  { code: "51297", name: "Crescent MFB" },
  { code: "090560", name: "Crust Microfinance Bank" },
  { code: "50216", name: "CRUTECH MICROFINANCE BANK LTD" },
  { code: "51368", name: "Dash Microfinance Bank" },
  { code: "51334", name: "Davenport MICROFINANCE BANK" },
  { code: "51450", name: "Dillon Microfinance Bank" },
  { code: "50162", name: "Dot Microfinance Bank" },
  { code: "50922", name: "EBSU Microfinance Bank" },
  { code: "050", name: "Ecobank Nigeria" },
  { code: "50263", name: "Ekimogun MFB" },
  { code: "098", name: "Ekondo Microfinance Bank" },
  { code: "51475", name: "Ethica MFB" },
  { code: "090678", name: "EXCEL FINANCE BANK" },
  { code: "50126", name: "Eyowo" },
  { code: "51318", name: "Fairmoney Microfinance Bank" },
  { code: "51241", name: "FCMB MFB" },
  { code: "50298", name: "Fedeth MFB" },
  { code: "050002", name: "Fewchore Finance Company Limited" },
  { code: "51110", name: "FFS Microfinance Bank" },
  { code: "070", name: "Fidelity Bank" },
  { code: "51314", name: "Firmus MFB" },
  { code: "011", name: "First Bank of Nigeria" },
  { code: "214", name: "First City Monument Bank" },
  { code: "50934", name: "First Option MFB" },
  { code: "090164", name: "FIRST ROYAL MICROFINANCE BANK" },
  { code: "51333", name: "FIRSTMIDAS MFB" },
  { code: "413", name: "FirstTrust Mortgage Bank Nigeria" },
  { code: "090567", name: "Flutterwave MFB" },
  { code: "D53", name: "Fortress MFB" },
  { code: "501", name: "FSDH Merchant Bank Limited" },
  { code: "832", name: "FUTMINNA MICROFINANCE BANK" },
  { code: "MFB51093", name: "Garun Mallam MFB" },
  { code: "812", name: "Gateway Mortgage Bank LTD" },
  { code: "00103", name: "Globus Bank" },
  { code: "090574", name: "Goldman MFB" },
  { code: "100022", name: "GoMoney" },
  { code: "090664", name: "GOOD SHEPHERD MICROFINANCE BANK" },
  { code: "50739", name: "Goodnews Microfinance Bank" },
  { code: "562", name: "Greenwich Merchant Bank" },
  { code: "51276", name: "GROOMING MICROFINANCE BANK" },
  { code: "50368", name: "GTI MFB" },
  { code: "058", name: "Guaranty Trust Bank" },
  { code: "51251", name: "Hackman Microfinance Bank" },
  { code: "90065", name: "Haggai Mortgage Bank" },
  { code: "50383", name: "Hasal Microfinance Bank" },
  { code: "51364", name: "Hayat Trust MFB" },
  { code: "120002", name: "HopePSB" },
  { code: "51211", name: "IBANK Microfinance Bank" },
  { code: "51279", name: "IBBU MFB" },
  { code: "51244", name: "Ibile Microfinance Bank" },
  { code: "90012", name: "Ibom Mortgage Bank" },
  { code: "50439", name: "Ikoyi Osun MFB" },
  { code: "50442", name: "Ilaro Poly Microfinance Bank" },
  { code: "50453", name: "Imowo MFB" },
  { code: "415", name: "IMPERIAL HOMES MORTAGE BANK" },
  { code: "51392", name: "INDULGE MFB" },
  { code: "51462", name: "INEBA GOGO MFB" },
  { code: "50457", name: "Infinity MFB" },
  { code: "070016", name: "Infinity trust  Mortgage Bank" },
  { code: "090701", name: "ISUA MFB" },
  { code: "301", name: "Jaiz Bank" },
  { code: "402", name: "Jubilee Life Mortgage Bank" },
  { code: "50502", name: "Kadpoly MFB" },
  { code: "51308", name: "KANOPOLY MFB" },
  { code: "5129", name: "Kayvee Microfinance Bank" },
  { code: "90028", name: "Kebbi Homes Savings and Loans Limited" },
  { code: "082", name: "Keystone Bank" },
  { code: "899", name: "Kolomoni MFB" },
  { code: "100025", name: "KONGAPAY (Kongapay Technologies Limited)(formerly Zinternet)" },
  { code: "50200", name: "Kredi Money MFB LTD" },
  { code: "50211", name: "Kuda Bank" },
  { code: "90052", name: "Lagos Building Investment Company Plc." },
  { code: "091003", name: "Lemmy MFB" },
  { code: "090420", name: "Letshego Microfinance Bank" },
  { code: "50549", name: "Links MFB" },
  { code: "031", name: "Living Trust Mortgage Bank" },
  { code: "50491", name: "LOMA MFB" },
  { code: "303", name: "Lotus Bank" },
  { code: "51444", name: "Maal MFB" },
  { code: "090171", name: "MAINSTREET MICROFINANCE BANK" },
  { code: "50563", name: "Mayfair MFB" },
  { code: "90003", name: "Mayfresh Mortgage Bank" },
  { code: "50570", name: "Mega Microfinance Bank" },
  { code: "MFB51116M", name: "Michael Okpara UniAgric Microfinance Bank" },
  { code: "50304", name: "Mint MFB" },
  { code: "09", name: "MINT-FINEX MFB" },
  { code: "946", name: "Money Master PSB" },
  { code: "50515", name: "Moniepoint MFB" },
  { code: "120003", name: "MTN Momo PSB" },
  { code: "090190", name: "MUTUAL BENEFITS MICROFINANCE BANK" },
  { code: "090679", name: "NDCC MICROFINANCE BANK" },
  { code: "51361", name: "NET MICROFINANCE BANK" },
  { code: "51142", name: "Nigerian Navy Microfinance Bank Limited" },
  { code: "51304", name: "NIRSAL MICROFINANCE" },
  { code: "50072", name: "Nombank MFB" },
  { code: "561", name: "NOVA BANK" },
  { code: "51371", name: "Novus MFB" },
  { code: "50629", name: "NPF MICROFINANCE BANK" },
  { code: "51261", name: "NSUK MICROFINANACE BANK" },
  { code: "50689", name: "Olabisi Onabanjo University Microfinance Bank" },
  { code: "50697", name: "OLUCHUKWU MICROFINANCE BANK LTD" },
  { code: "999992", name: "OPay Digital Services Limited (OPay)" },
  { code: "107", name: "Optimus Bank Limited" },
  { code: "51477", name: "Pact Microfinance Bank" },
  { code: "100002", name: "Paga" },
  { code: "999991", name: "PalmPay" },
  { code: "104", name: "Parallex Bank" },
  { code: "311", name: "Parkway - ReadyCash" },
  { code: "090680", name: "PATHFINDER MICROFINANCE BANK LIMITED" },
  { code: "51457", name: "Paystack MFB" },
  { code: "100039", name: "Paystack-Titan" },
  { code: "50743", name: "Peace Microfinance Bank" },
  { code: "51226", name: "PECANTRUST MICROFINANCE BANK LIMITED" },
  { code: "51146", name: "Personal Trust MFB" },
  { code: "50746", name: "Petra Mircofinance Bank Plc" },
  { code: "MFB51452", name: "Pettysave MFB" },
  { code: "050021", name: "PFI FINANCE COMPANY LIMITED" },
  { code: "268", name: "Platinum Mortgage Bank" },
  { code: "00716", name: "Pocket App" },
  { code: "076", name: "Polaris Bank" },
  { code: "50864", name: "Polyunwana MFB" },
  { code: "105", name: "PremiumTrust Bank" },
  { code: "50739", name: "Prospa Capital Microfinance Bank" },
  { code: "050023", name: "PROSPERIS FINANCE LIMITED" },
  { code: "101", name: "Providus Bank" },
  { code: "51293", name: "QuickFund MFB" },
  { code: "502", name: "Rand Merchant Bank" },
  { code: "090496", name: "RANDALPHA MICROFINANCE BANK" },
  { code: "50130", name: "Rank MFB" },
  { code: "90067", name: "Refuge Mortgage Bank" },
  { code: "50761", name: "REHOBOTH MICROFINANCE BANK" },
  { code: "50994", name: "Rephidim Microfinance Bank" },
  { code: "51375", name: "Retrust Mfb" },
  { code: "51108", name: "Rex Microfinance Bank" },
  { code: "51286", name: "Rigo Microfinance Bank Limited" },
  { code: "50767", name: "ROCKSHIELD MICROFINANCE BANK" },
  { code: "125", name: "Rubies MFB" },
  { code: "51113", name: "Safe Haven MFB" },
  { code: "40165", name: "SAGE GREY FINANCE LIMITED" },
  { code: "50582", name: "Shield MFB" },
  { code: "106", name: "Signature Bank Ltd" },
  { code: "51062", name: "Solid Allianze MFB" },
  { code: "50800", name: "Solid Rock MFB" },
  { code: "51310", name: "Sparkle Microfinance Bank" },
  { code: "50756", name: "SPECTRUM MFB LTD" },
  { code: "51429", name: "Springfield Microfinance Bank" },
  { code: "221", name: "Stanbic IBTC Bank" },
  { code: "068", name: "Standard Chartered Bank" },
  { code: "090162", name: "STANFORD MICROFINANCE BANK" },
  { code: "50809", name: "STATESIDE MICROFINANCE BANK" },
  { code: "070022", name: "STB Mortgage Bank" },
  { code: "51253", name: "Stellas MFB" },
  { code: "232", name: "Sterling Bank" },
  { code: "00305", name: "Summit Bank" },
  { code: "100", name: "Suntrust Bank" },
  { code: "50968", name: "Supreme MFB" },
  { code: "51056", name: "Sycamore Microfinance Bank" },
  { code: "302", name: "TAJ Bank" },
  { code: "51269", name: "Tangerine Money" },
  { code: "109", name: "Tatum Bank" },
  { code: "51403", name: "TENN" },
  { code: "677", name: "Think Finance Microfinance Bank" },
  { code: "102", name: "Titan Bank" },
  { code: "090708", name: "TransPay MFB" },
  { code: "51118", name: "TRUSTBANC J6 MICROFINANCE BANK" },
  { code: "50840", name: "U and C MFB" },
  { code: "50840", name: "U&C Microfinance Bank Ltd (U AND C MFB)" },
  { code: "090706", name: "UCEE MFB" },
  { code: "51322", name: "Uhuru MFB" },
  { code: "51080", name: "Ultraviolet Microfinance Bank" },
  { code: "50870", name: "Unaab Microfinance Bank Limited" },
  { code: "51447", name: "UNIABUJA MFB" },
  { code: "50871", name: "Unical MFB" },
  { code: "51316", name: "Unilag Microfinance Bank" },
  { code: "50875", name: "UNIMAID MICROFINANCE BANK" },
  { code: "032", name: "Union Bank of Nigeria" },
  { code: "033", name: "United Bank For Africa" },
  { code: "215", name: "Unity Bank" },
  { code: "50880", name: "UNIUYO Microfinance Bank Ltd" },
  { code: "50894", name: "Uzondu Microfinance Bank Awka Anambra State" },
  { code: "050020", name: "Vale Finance Limited" },
  { code: "566", name: "VFD Microfinance Bank Limited" },
  { code: "51085", name: "Victory MFB" },
  { code: "51355", name: "Waya Microfinance Bank" },
  { code: "035", name: "Wema Bank" },
  { code: "51386", name: "Weston Charis MFB" },
  { code: "402001", name: "Whitecrust Finance Company" },
  { code: "100040", name: "Xpress Wallet" },
  { code: "51253", name: "YCT MFB" },
  { code: "594", name: "Yes MFB" },
  { code: "00zap", name: "Zap" },
  { code: "057", name: "Zenith Bank" },
  { code: "51373", name: "Zitra MFB" },
];