// Mirrors modules/services/invoicing/paystack_subaccount_service.py
// PaystackSubaccountService.BANK_NAME_MAP exactly — there's no banks-list
// endpoint on the backend, so this is the same fixed map the backend itself
// resolves bank_name from. Keep in sync if that map changes.

export const NIGERIAN_BANKS: { code: string; name: string }[] = [
  // ── Commercial Banks ──────────────────────────────────────────
  { code: "044",    name: "Access Bank" },
  { code: "023",    name: "Citibank Nigeria" },
  { code: "063",    name: "Diamond Bank" },
  { code: "050",    name: "Ecobank Nigeria" },
  { code: "084",    name: "Enterprise Bank" },
  { code: "070",    name: "Fidelity Bank" },
  { code: "011",    name: "First Bank of Nigeria" },
  { code: "214",    name: "First City Monument Bank (FCMB)" },
  { code: "058",    name: "Guaranty Trust Bank (GTBank)" },
  { code: "030",    name: "Heritage Bank" },
  { code: "301",    name: "Jaiz Bank" },
  { code: "082",    name: "Keystone Bank" },
  { code: "000029", name: "Lotus Bank" },
  { code: "076",    name: "Polaris Bank" },
  { code: "000031", name: "Premium Trust Bank" },
  { code: "101",    name: "Providus Bank" },
  { code: "039",    name: "Stanbic IBTC Bank" },
  { code: "068",    name: "Standard Chartered Bank Nigeria" },
  { code: "232",    name: "Sterling Bank" },
  { code: "100",    name: "SunTrust Bank Nigeria" },
  { code: "000026", name: "Taj Bank" },
  { code: "000025", name: "Titan Trust Bank" },
  { code: "032",    name: "Union Bank of Nigeria" },
  { code: "033",    name: "United Bank for Africa (UBA)" },
  { code: "215",    name: "Unity Bank" },
  { code: "035",    name: "Wema Bank" },
  { code: "057",    name: "Zenith Bank" },
  { code: "000027", name: "Globus Bank" },
 
  // ── Payment Service Banks ─────────────────────────────────────
  { code: "120001", name: "9PSB" },
  { code: "120002", name: "Hope Payment Service Bank" },
  { code: "120003", name: "Momo Payment Service Bank (MTN)" },
 
  // ── Digital / Fintech Banks ───────────────────────────────────
  { code: "100026", name: "Carbon" },
  { code: "100032", name: "Contec Global (Nownow)" },
  { code: "090267", name: "Kuda Microfinance Bank" },
  { code: "090551", name: "FairMoney Microfinance Bank" },
  { code: "090405", name: "Moniepoint Microfinance Bank" },
  { code: "100033", name: "PalmPay" },
  { code: "327",    name: "Paga" },
  { code: "329",    name: "PayAttitude Online" },
  { code: "305",    name: "Paycom (OPay)" },
  { code: "090325", name: "Sparkle Microfinance Bank" },
  { code: "566",    name: "VFD Microfinance Bank" },
  { code: "100052", name: "Access Yellow (Beta)" },
  { code: "090455", name: "Mkobo Microfinance Bank" },
  { code: "306",    name: "eTranzact" },
  { code: "309",    name: "First Monnie Wallet" },
 
  // ── Microfinance Banks ────────────────────────────────────────
  { code: "090134", name: "Accion Microfinance Bank" },
  { code: "090160", name: "Addosser Microfinance Bank" },
  { code: "090270", name: "AB Microfinance Bank" },
  { code: "090529", name: "Ampersand Microfinance Bank" },
  { code: "090180", name: "AMJU Microfinance Bank" },
  { code: "090645", name: "AMUCHA Microfinance Bank" },
  { code: "090264", name: "Auchi Microfinance Bank" },
  { code: "090097", name: "Ekondo Microfinance Bank" },
  { code: "090539", name: "Enrich Microfinance Bank" },
  { code: "090291", name: "Hala Credit Microfinance Bank" },
  { code: "090147", name: "Hackman Microfinance Bank" },
  { code: "090118", name: "Ibile Microfinance Bank" },
  { code: "090602", name: "Kenechukwu Microfinance Bank" },
  { code: "090380", name: "Kredi Microfinance Bank" },
  { code: "090177", name: "Lapo Microfinance Bank" },
  { code: "090420", name: "Letshego Microfinance Bank" },
  { code: "090171", name: "Mainstreet Microfinance Bank" },
  { code: "090194", name: "Nirsal Microfinance Bank" },
  { code: "090345", name: "OAU Microfinance Bank" },
  { code: "070008", name: "Page Financials" },
  { code: "526",    name: "Parallex Microfinance Bank" },
  { code: "090499", name: "Pristine Divitis Microfinance Bank" },
  { code: "090503", name: "Projetcs Microfinance Bank" },
  { code: "090496", name: "Randalpha Microfinance Bank" },
  { code: "090198", name: "RenMoney Microfinance Bank" },
  { code: "090138", name: "Royal Exchange Microfinance Bank" },
  { code: "090502", name: "Shalom Microfinance Bank" },
  { code: "090251", name: "UNN Microfinance Bank" },
  { code: "090504", name: "Zikora Microfinance Bank" },
  { code: "090495", name: "Good News Microfinance Bank" },
];
