// POS sale receipt — print + PDF, mirrors lib/pdf-receipt.ts's jsPDF + html2canvas
// approach but laid out as a narrow till receipt instead of an A4 invoice.

import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import type { SaleDetail } from "@/types/pos";
import { formatDateTime, formatMoney } from "@/lib/format";

const colors = {
  surface: "#ffffff",
  surfaceMuted: "#e7eef6",
  ink: "#101728",
  body: "#4b5366",
  muted: "#8a93a6",
  line: "#dce3ed",
  primary: "#1849d6",
};

function buildReceiptHtml(sale: SaleDetail): string {
  const itemRows = sale.items
    .map(
      (item) => `
    <tr>
      <td style="padding:6px 0;color:${colors.ink};font-size:12px;">${item.item_name}</td>
      <td style="padding:6px 0;text-align:right;font-family:'Courier New',monospace;font-size:12px;color:${colors.body};">${item.quantity}</td>
      <td style="padding:6px 0;text-align:right;font-family:'Courier New',monospace;font-size:12px;color:${colors.ink};">${formatMoney(item.amount)}</td>
    </tr>`,
    )
    .join("");

  const logoBlock = sale.merchant_logo
    ? `<img src="${sale.merchant_logo}" alt="${sale.merchant_name}" style="height:36px;width:36px;border-radius:6px;object-fit:cover;" />`
    : `<div style="font-size:18px;font-weight:700;color:${colors.primary};letter-spacing:-0.02em;">${sale.merchant_name}</div>`;

  return `
    <div style="width:340px;background:${colors.surface};font-family:'Inter',Arial,sans-serif;padding:24px;box-sizing:border-box;">
      <div style="text-align:center;margin-bottom:16px;">
        <div style="display:flex;justify-content:center;margin-bottom:8px;">${logoBlock}</div>
        ${sale.merchant_logo ? `<div style="font-size:14px;font-weight:600;color:${colors.ink};">${sale.merchant_name}</div>` : ""}
      </div>

      <div style="border-top:1px dashed ${colors.line};border-bottom:1px dashed ${colors.line};padding:10px 0;margin-bottom:14px;text-align:center;">
        <div style="font-family:'Courier New',monospace;font-size:13px;font-weight:600;color:${colors.ink};">${sale.sale_number}</div>
        <div style="font-size:11px;color:${colors.muted};margin-top:2px;">${formatDateTime(sale.created_at)}</div>
        ${sale.recorded_by_name ? `<div style="font-size:11px;color:${colors.muted};">Served by ${sale.recorded_by_name}</div>` : ""}
      </div>

      <table style="width:100%;border-collapse:collapse;margin-bottom:12px;">
        <thead>
          <tr style="border-bottom:1px solid ${colors.line};">
            <th style="padding:0 0 6px;text-align:left;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:${colors.muted};">Item</th>
            <th style="padding:0 0 6px;text-align:right;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:${colors.muted};">Qty</th>
            <th style="padding:0 0 6px;text-align:right;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:0.06em;color:${colors.muted};">Amount</th>
          </tr>
        </thead>
        <tbody>${itemRows}</tbody>
      </table>

      <div style="display:flex;justify-content:space-between;padding-top:10px;border-top:1px solid ${colors.line};font-size:15px;font-weight:700;color:${colors.ink};">
        <span>Total</span><span style="font-family:'Courier New',monospace;">${formatMoney(sale.total_amount)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding-top:6px;font-size:12px;color:${colors.body};">
        <span>Payment</span><span style="text-transform:capitalize;">${sale.payment_method}</span>
      </div>

      <div style="margin-top:20px;padding-top:12px;border-top:1px dashed ${colors.line};text-align:center;">
        <p style="font-size:11px;color:${colors.muted};margin:0;">Thank you for your purchase.</p>
        <p style="font-size:9px;color:${colors.muted};margin:6px 0 0;">Generated by Entacrest Business Suite · ebs.entacrest.com</p>
      </div>
    </div>
  `;
}

export async function downloadSaleReceiptPdf(sale: SaleDetail): Promise<void> {
  const container = document.createElement("div");
  container.style.position = "fixed";
  container.style.top = "-9999px";
  container.style.left = "-9999px";
  container.style.zIndex = "-1";
  container.innerHTML = buildReceiptHtml(sale);
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container.firstElementChild as HTMLElement, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
    });

    const imgData = canvas.toDataURL("image/png");
    const imgWidthPx = canvas.width;
    const imgHeightPx = canvas.height;

    // Fit the PDF page to the receipt itself rather than an A4 sheet — a
    // till receipt is short and narrow, not a full page.
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "px",
      format: [imgWidthPx / 2, imgHeightPx / 2],
    });
    pdf.addImage(imgData, "PNG", 0, 0, imgWidthPx / 2, imgHeightPx / 2);
    pdf.save(`receipt-${sale.sale_number}.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}

export function printSaleReceipt(sale: SaleDetail): void {
  const printWindow = window.open("", "_blank", "width=420,height=640");
  if (!printWindow) return;

  printWindow.document.write(`
    <!doctype html>
    <html>
      <head>
        <title>Receipt ${sale.sale_number}</title>
        <meta charset="utf-8" />
      </head>
      <body style="margin:0;display:flex;justify-content:center;background:#fff;">
        ${buildReceiptHtml(sale)}
      </body>
    </html>
  `);
  printWindow.document.close();

  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
    printWindow.close();
  };
}
